export const HYDERABAD_LOCALITIES = [
  "Gachibowli",
  "Madhapur",
  "Kondapur",
  "Banjara Hills",
  "Jubilee Hills",
  "Kukatpally",
  "Hitech City",
  "Miyapur",
  "Manikonda",
  "Financial District",
  "Begumpet",
  "Secunderabad",
  "Uppal",
  "Kompally",
  "LB Nagar",
  "Nallagandla",
  "Tellapur",
  "Attapur",
  "Somajiguda",
  "Himayatnagar",
];
