import { NextRequest, NextResponse } from "next/server";
import { readFile } from "node:fs/promises";
import path from "node:path";

// User-uploaded files (listing/project/home-tile photos, site logo, favicon)
// are served through this route instead of a plain public/uploads/<file>
// static URL. Next's standalone production server (output: standalone)
// resolves public/ static assets from a manifest it builds once at process
// boot — a file written to public/uploads/ *after* the server has started
// (i.e. any real user upload, since uploads always happen at runtime) 404s
// until the process restarts, even though the file is sitting right there on
// disk (verified empirically against this exact Next.js version). Reading
// the file from disk on every request here sidesteps that entirely, at the
// cost of a bit more per-request work than a truly static file would take —
// an easy trade given uploads aren't hot-path traffic.
const UPLOAD_DIR = path.join(process.cwd(), "public", "uploads");

// Only ever generated by crypto.randomUUID() + one of these extensions (see
// lib/uploads.ts) — this also rules out path traversal (no "..", "/", etc.).
const SAFE_FILENAME = /^[a-f0-9-]{36}\.(jpg|jpeg|png|webp|gif|ico|svg)$/i;

const CONTENT_TYPES: Record<string, string> = {
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  png: "image/png",
  webp: "image/webp",
  gif: "image/gif",
  ico: "image/x-icon",
  svg: "image/svg+xml",
};

export async function GET(_req: NextRequest, { params }: { params: Promise<{ filename: string }> }) {
  const { filename } = await params;
  if (!SAFE_FILENAME.test(filename)) {
    return new NextResponse("Not found", { status: 404 });
  }

  try {
    const buffer = await readFile(path.join(UPLOAD_DIR, filename));
    const ext = filename.split(".").pop()!.toLowerCase();
    return new NextResponse(new Uint8Array(buffer), {
      status: 200,
      headers: {
        "Content-Type": CONTENT_TYPES[ext] ?? "application/octet-stream",
        // Filenames are random and never reused/overwritten in place (a new
        // upload always gets a fresh UUID) — safe to cache indefinitely.
        "Cache-Control": "public, max-age=31536000, immutable",
      },
    });
  } catch {
    return new NextResponse("Not found", { status: 404 });
  }
}
